# Generated by Django 5.2.9 on 2025-12-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                default="projects/default.jpg", upload_to="projects/%Y/%m/%d/"
            ),
        ),
    ]
