# Generated by Django 5.2.9 on 2025-12-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("satisfied_customers", models.IntegerField()),
                ("website_created", models.IntegerField()),
                ("specialist_expert", models.IntegerField()),
                ("years_of_experience", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(
                default="course/default.jpg", upload_to="services_images/%Y/%m/%d/"
            ),
        ),
    ]
