# Generated by Django 5.2.9 on 2025-12-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_statistics_alter_service_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("percent", models.IntegerField(default=0)),
            ],
        ),
    ]
